# Generated by Django 2.1 on 2018-08-30 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(null=True)),
                ('liked_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('url_problem', models.URLField(null=True)),
                ('solution', models.CharField(blank=True, max_length=255, null=True)),
                ('url_solution', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('test_name', models.CharField(blank=True, max_length=255, null=True)),
                ('test_url', models.URLField(blank=True, null=True)),
                ('top_coder', models.CharField(blank=True, max_length=255, null=True)),
                ('top_contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('top_improver', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Session_Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Session')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Session'),
        ),
        migrations.AddField(
            model_name='editorial',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Problem'),
        ),
        migrations.AddField(
            model_name='editorial',
            name='user_submitted',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile'),
        ),
    ]
