# Generated by Django 2.1 on 2018-09-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('tag', models.ManyToManyField(blank=True, to='events.Tags')),
            ],
        ),
    ]
