# Generated by Django 2.1 on 2018-08-30 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event_ranking',
            name='session',
        ),
        migrations.RemoveField(
            model_name='event_ranking',
            name='user',
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='liked_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Event_Ranking',
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='events.Tags'),
        ),
    ]
