# Generated by Django 2.1 on 2018-09-01 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_readingmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingmaterial',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.Session'),
        ),
    ]
