# Generated by Django 2.1 on 2018-08-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('events', '0002_auto_20180830_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session_Ranking',
            new_name='Ranking',
        ),
    ]
