# Generated by Django 2.1 on 2018-09-01 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_readingmaterial_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persessionuserlikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile'),
        ),
    ]
