# Generated by Django 2.1 on 2018-09-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_pic',
            field=models.URLField(default='https://cdn4.iconfinder.com/data/icons/ui-standard/96/People-512.png'),
        ),
    ]
